mickey

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,23 @@
 #!/usr/bin/env bash
-# transfers a file from our client to a server
 
-if [ "$#" -ne 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY=$4
+
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
+
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+    echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
 else
-    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+    echo "Error transferring file. Please check your parameters and try again."
 fi
